<strong>Hi There,</strong>
<br />
    <div style="margin:0; padding:0;">
        <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:20px;">Somebody contacted you on FrumCare with the following details:</p>
    </div>
<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Name: <?php echo $name;?></div>
<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Email: <?php echo $email;?></div>
<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Contact Number: <?php echo $phonenumber;?></div>
<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Comment: <?php echo $comment;?></div>
<?php if($filename !=''){?>
  <div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Please find the file attachment below</div>
<?php }?>


Thank you,
<br />
FRUMCARE team
<br />
 —
 <br />
 The email is auto generated by frumcare.com website.
