<strong>Hi <?php echo $name ?>,</strong>
<br />
    <div style="margin:0; padding:0;">
        <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:20px;"> Thank you for placing an ad on FrumCare.com!<br>Your ad will be placed on the site after it is approved by our team.<p>
        	<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Click <a href="<?php echo site_url();?>login">here</a> to login to your FrumCare account.</div>
    </div>
<br />
Thanks,
<br />
FrumCare.com
<br />
 
 <br />
 The email is auto generated by frumcare.com website.
 
 
 
 
  