<strong>Hi <?php echo $name ?>,</strong>
<br />
    <div style="margin:0; padding:0;">
        <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:20px;">Your email has been successfully verfied.<br>Please use the following details to login your FrumCare account.<p>
        	<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">User email: <?php echo $email;?></div>
        	<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Password: <?php echo $password;?></div>
        	<div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Link: <a href="<?php echo site_url();?>login">Click Here</a></div>
    </div>
<br />
Thank you,
<br />
FrumCare Team
<br />
 
 <br />
 The email is auto generated by frumcare.com website.
