<strong>Hi <?php echo $name ?>,</strong>
<br />
    <div style="margin:0; padding:0;">
        <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:20px;"> New Image has been added in an ad on FrumCare.com!<p>
            <div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Please Login to admin to verify</div>
    </div>
<br />
Thanks,
<br />
FrumCare.com
<br />

 <br />
 The email is auto generated by frumcare.com website.





