<strong>Hi There,</strong>

<br />
    <div style="margin:0; padding:0;">
        <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:20px;">Your password has been updated Please use the following password:</p>
        <div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Password: <?php echo $password;?></div>
        <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:20px;">Plese click the following link to log in:<?php echo $link;?></p>
    </div>
<br />
Thank you,
<br />
FRUMCare team
<br />
 —
 <br />
 The email is auto generated by frumcare.com website.
