<strong>Hi There,</strong>
<br />
    <div style="margin:0; padding:0;">
        <p style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:20px;">Please find the reply in bold for your ticket you have submitted in FRUMCARE</p>
        <div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Your Query: <?php echo nl2br($subject);?></div>
        <div style="font-family:Arial, Helvetica, sans-serif; font-size:13px; margin-bottom:5px;">Our  Answer: <strong><?php echo nl2br($reply_text);?></strong></div>
    </div>
<br />
Thanks you,
<br />
FRUMCARE team
<br />
 —
 <br />
 The email is auto generated by frumcare.com website.

